CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(254),
    phone varchar(30)
);

CREATE TABLE suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(254),
    phone varchar(30)
);
