CREATE TABLE purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(50) NOT NULL UNIQUE,
    date date NOT NULL,
    supplier_id bigint NOT NULL REFERENCES suppliers(id),
    supplier_name varchar(120) NOT NULL,
    notes varchar(1000),
    total numeric(14,2) NOT NULL CHECK (total >= 0)
);

CREATE TABLE purchase_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id bigint NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES products(id),
    product_name varchar(120) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0 AND quantity <= 10000),
    unit_price numeric(14,2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(14,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX ix_purchase_supplier ON purchases(supplier_id);
CREATE INDEX ix_purchase_item_parent ON purchase_items(purchase_id);
CREATE INDEX ix_purchase_item_product ON purchase_items(product_id);
