CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id uuid NOT NULL UNIQUE,
    invoice_id bigint REFERENCES sales_invoices(id),
    purchase_id bigint REFERENCES purchases(id),
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    method varchar(20) NOT NULL CHECK (method IN ('CASH', 'BANK_TRANSFER')),
    paid_on date NOT NULL,
    reference varchar(200),
    CHECK ((invoice_id IS NOT NULL AND purchase_id IS NULL)
        OR (invoice_id IS NULL AND purchase_id IS NOT NULL))
);

CREATE INDEX ix_payment_invoice ON payments(invoice_id);
CREATE INDEX ix_payment_purchase ON payments(purchase_id);
