import type { Invoice } from "./types";
import { formatMoney } from "./utils";

type ExportFormat = "pdf" | "png";

function safeName(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, "-").replace(/^-|-$/g, "");
}

function canvasBlob(canvas: HTMLCanvasElement, type: string, quality?: number) {
  return new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("Could not create invoice file")), type, quality));
}

function drawText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, options: { color?: string; font?: string; align?: CanvasTextAlign } = {}) {
  ctx.fillStyle = options.color ?? "#172033";
  ctx.font = options.font ?? "28px Arial, sans-serif";
  ctx.textAlign = options.align ?? "left";
  ctx.fillText(text, x, y);
}

function rule(ctx: CanvasRenderingContext2D, y: number) {
  ctx.strokeStyle = "#dfe4eb";
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(82, y);
  ctx.lineTo(1158, y);
  ctx.stroke();
}

export function renderInvoiceCanvas(invoice: Invoice) {
  const width = 1240;
  const height = Math.max(1754, 1080 + invoice.items.length * 82);
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Invoice rendering is not supported in this browser");

  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, height);
  ctx.fillStyle = "#edf5ff";
  ctx.fillRect(0, 0, width, 18);

  drawText(ctx, "SIYOTHSOFT", 82, 112, { font: "700 42px Arial, sans-serif" });
  drawText(ctx, "ERP", 371, 112, { color: "#6b7280", font: "600 20px Arial, sans-serif" });
  drawText(ctx, "Business management workspace", 82, 154, { color: "#6b7280", font: "22px Arial, sans-serif" });
  drawText(ctx, "INVOICE", 1158, 108, { color: "#243b53", font: "700 52px Arial, sans-serif", align: "right" });
  drawText(ctx, invoice.number, 1158, 151, { color: "#526174", font: "24px Arial, sans-serif", align: "right" });
  rule(ctx, 205);

  drawText(ctx, "BILL TO", 82, 273, { color: "#6b7280", font: "700 18px Arial, sans-serif" });
  drawText(ctx, invoice.customerName, 82, 323, { font: "700 34px Arial, sans-serif" });
  drawText(ctx, "ISSUE DATE", 1158, 273, { color: "#6b7280", font: "700 18px Arial, sans-serif", align: "right" });
  drawText(ctx, invoice.date, 1158, 323, { font: "600 28px Arial, sans-serif", align: "right" });

  const tableTop = 410;
  ctx.fillStyle = "#f5f7fa";
  ctx.fillRect(82, tableTop, 1076, 64);
  drawText(ctx, "ITEM", 106, tableTop + 41, { color: "#526174", font: "700 18px Arial, sans-serif" });
  drawText(ctx, "QTY", 760, tableTop + 41, { color: "#526174", font: "700 18px Arial, sans-serif", align: "right" });
  drawText(ctx, "UNIT PRICE", 955, tableTop + 41, { color: "#526174", font: "700 18px Arial, sans-serif", align: "right" });
  drawText(ctx, "AMOUNT", 1134, tableTop + 41, { color: "#526174", font: "700 18px Arial, sans-serif", align: "right" });

  let rowY = tableTop + 112;
  invoice.items.forEach((item) => {
    drawText(ctx, item.productName, 106, rowY, { font: "26px Arial, sans-serif" });
    drawText(ctx, String(item.quantity), 760, rowY, { font: "26px Arial, sans-serif", align: "right" });
    drawText(ctx, `LKR ${formatMoney(item.unitPrice)}`, 955, rowY, { font: "26px Arial, sans-serif", align: "right" });
    drawText(ctx, `LKR ${formatMoney(item.lineTotal)}`, 1134, rowY, { font: "700 26px Arial, sans-serif", align: "right" });
    rule(ctx, rowY + 34);
    rowY += 82;
  });

  const totalsY = Math.max(rowY + 42, 760);
  const totalLine = (label: string, value: string, y: number, strong = false) => {
    drawText(ctx, label, 790, y, { color: "#526174", font: strong ? "700 25px Arial, sans-serif" : "24px Arial, sans-serif" });
    drawText(ctx, value, 1158, y, { font: strong ? "700 31px Arial, sans-serif" : "600 24px Arial, sans-serif", align: "right" });
  };
  totalLine("Invoice total", `LKR ${formatMoney(invoice.total)}`, totalsY);
  totalLine("Amount paid", invoice.documentStatus === "ISSUED" ? `LKR ${formatMoney(invoice.amountPaid)}` : "—", totalsY + 56);
  ctx.fillStyle = "#edf5ff";
  ctx.fillRect(760, totalsY + 87, 398, 74);
  totalLine("Balance due", invoice.documentStatus === "ISSUED" ? `LKR ${formatMoney(invoice.balance)}` : "—", totalsY + 136, true);

  if (invoice.notes) {
    drawText(ctx, "NOTES", 82, totalsY + 238, { color: "#6b7280", font: "700 18px Arial, sans-serif" });
    drawText(ctx, invoice.notes.slice(0, 110), 82, totalsY + 280, { color: "#526174", font: "23px Arial, sans-serif" });
  }

  rule(ctx, height - 125);
  drawText(ctx, "Thank you for your business.", 82, height - 72, { color: "#526174", font: "22px Arial, sans-serif" });
  drawText(ctx, "Generated by SiyothSoft ERP", 1158, height - 72, { color: "#8a94a3", font: "20px Arial, sans-serif", align: "right" });
  return canvas;
}

function joinBytes(parts: Uint8Array[]) {
  const output = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0));
  let offset = 0;
  parts.forEach((part) => { output.set(part, offset); offset += part.length; });
  return output;
}

async function createPdfBlob(canvas: HTMLCanvasElement) {
  const jpeg = new Uint8Array(await (await canvasBlob(canvas, "image/jpeg", .94)).arrayBuffer());
  const encode = (value: string) => new TextEncoder().encode(value);
  const parts: Uint8Array[] = [encode("%PDF-1.4\n")];
  const offsets = [0];
  let length = parts[0].length;
  const addObject = (id: number, content: Uint8Array) => {
    offsets[id] = length;
    const opening = encode(`${id} 0 obj\n`);
    const closing = encode("\nendobj\n");
    parts.push(opening, content, closing);
    length += opening.length + content.length + closing.length;
  };
  addObject(1, encode("<< /Type /Catalog /Pages 2 0 R >>"));
  addObject(2, encode("<< /Type /Pages /Kids [3 0 R] /Count 1 >>"));
  addObject(3, encode("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>"));
  addObject(4, joinBytes([encode(`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`), jpeg, encode("\nendstream")]));
  const command = encode("q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ");
  addObject(5, joinBytes([encode(`<< /Length ${command.length} >>\nstream\n`), command, encode("\nendstream")]));
  const xrefOffset = length;
  const xref = [`xref\n0 6\n0000000000 65535 f \n`, ...offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`), `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`].join("");
  parts.push(encode(xref));
  return new Blob([joinBytes(parts)], { type: "application/pdf" });
}

export async function shareInvoice(invoice: Invoice, format: ExportFormat) {
  const canvas = renderInvoiceCanvas(invoice);
  const blob = format === "pdf" ? await createPdfBlob(canvas) : await canvasBlob(canvas, "image/png");
  const extension = format === "pdf" ? "pdf" : "png";
  const file = new File([blob], `${safeName(invoice.number || "invoice")}.${extension}`, { type: blob.type });
  const shareData = { title: `Invoice ${invoice.number}`, text: `Invoice for ${invoice.customerName}`, files: [file] };
  if (navigator.share && (!navigator.canShare || navigator.canShare(shareData))) {
    await navigator.share(shareData);
    return "shared" as const;
  }
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = file.name;
  link.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  return "downloaded" as const;
}
